# Generated by Django 4.0 on 2022-01-11 06:53

import bbs.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='タイトル')),
                ('summary', models.CharField(blank=True, max_length=128, null=True, verbose_name='概要')),
                ('img', models.ImageField(blank=True, null=True, upload_to=bbs.models.get_upload_to, validators=[bbs.models.image_size], verbose_name='写真ファイル')),
                ('rank', models.IntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('alive', models.BooleanField(default=True, verbose_name='有効')),
            ],
        ),
    ]
