# Generated by Django 4.0 on 2022-01-10 04:21

import bbs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='src',
        ),
        migrations.AddField(
            model_name='file',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=bbs.models.get_upload_to, verbose_name='写真ファイル'),
        ),
    ]
