# Generated by Django 4.0 on 2022-01-10 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_remove_file_src_file_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
