# Generated by Django 4.0 on 2022-01-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_remove_file_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='summary',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='概要'),
        ),
    ]
